apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-5-0-0
  labels:
    app: kibana-5-0-0
spec:
  replicas: 1
  selector:
    name: kibana-5-0-0
  template:
    metadata:
      labels:
        name: kibana-5-0-0
    spec:
      containers:
      - name: kibana-5-0-0
        image: fluxcapacitor/kibana-5.0.0
        imagePullPolicy: "Never"
        ports:
        - containerPort: 5601
      nodeSelector:
        training: "true"
