apiVersion: v1
kind: Service
metadata:
  name: metastore-1-2-1
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - name: metastore-native
    port: 9083
    targetPort: 9083
  selector:
    name: metastore-1-2-1
