apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9200
        - containerPort: 9300
      nodeSelector:
        training: "true"
