apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-5-0-0
spec:
  type: NodePort
  ports:
  - name: native
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    name: elasticsearch-5-0-0
