apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-master-2-0-1
  labels:
    app: spark
    role: master
    version: 2.0.1
spec:
  replicas: 1
  selector:
    name: spark-master-2-0-1
  template:
    metadata:
      labels:
        name: spark-master-2-0-1
    spec:
      containers:
      - name: spark-master-2-0-1
        image: docker.io/fluxcapacitor/apachespark-master-2.0.1
        imagePullPolicy: "Never"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6060
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 4042
        - containerPort: 4043
        - containerPort: 4044
      nodeSelector:
        training: "true"
