apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: docker.io/fluxcapacitor/sql-mysql
        imagePullPolicy: "Never"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 3306
      nodeSelector:
        training: "true"
